---
- name: (Debian) install filezilla...
  when: ansible_os_family == 'Debian'
  apt: name=filezilla state=latest

- name: (RedHat) install filezilla...
  when: ansible_os_family == 'RedHat'
  yum: name=filezilla state=latest